import type { StyleSpecification } from 'maplibre-gl';
import { C } from '../ui/tokens';

// "Air Navigation Display" basemap on OpenFreeMap vector tiles (OpenMapTiles schema).
// Land and water only, hairline borders, airports emphasised, everything else muted or off.

export const FONT = ['Noto Sans Regular'];
export const FONT_BOLD = ['Noto Sans Bold'];

export function baseStyle(): StyleSpecification {
  return {
    version: 8,
    glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
    sources: {
      omt: { type: 'vector', url: 'https://tiles.openfreemap.org/planet' },
    },
    layers: [
      { id: 'land', type: 'background', paint: { 'background-color': C.mapLand } },
      {
        id: 'water',
        type: 'fill',
        source: 'omt',
        'source-layer': 'water',
        paint: { 'fill-color': C.mapWater, 'fill-antialias': true },
      },
      {
        id: 'waterway',
        type: 'line',
        source: 'omt',
        'source-layer': 'waterway',
        minzoom: 8,
        paint: { 'line-color': C.mapWater, 'line-width': ['interpolate', ['linear'], ['zoom'], 8, 0.4, 13, 1.6] },
      },
      {
        id: 'urban',
        type: 'fill',
        source: 'omt',
        'source-layer': 'landuse',
        minzoom: 8,
        filter: ['in', ['get', 'class'], ['literal', ['residential', 'commercial', 'industrial']]],
        paint: { 'fill-color': C.mapUrban, 'fill-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0, 10, 0.6] },
      },
      {
        id: 'boundary-state',
        type: 'line',
        source: 'omt',
        'source-layer': 'boundary',
        minzoom: 5,
        filter: ['all', ['==', ['get', 'admin_level'], 4], ['!=', ['get', 'maritime'], 1]],
        paint: { 'line-color': C.mapBorderFaint, 'line-width': 0.6, 'line-dasharray': [3, 2] },
      },
      {
        id: 'boundary-country',
        type: 'line',
        source: 'omt',
        'source-layer': 'boundary',
        filter: ['all', ['==', ['get', 'admin_level'], 2], ['!=', ['get', 'maritime'], 1]],
        paint: { 'line-color': C.mapBorder, 'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 10, 1.2] },
      },
      {
        id: 'road-primary',
        type: 'line',
        source: 'omt',
        'source-layer': 'transportation',
        minzoom: 9,
        filter: ['in', ['get', 'class'], ['literal', ['trunk', 'primary']]],
        paint: { 'line-color': C.mapRoad, 'line-width': ['interpolate', ['linear'], ['zoom'], 9, 0.5, 14, 2] },
      },
      {
        id: 'motorway',
        type: 'line',
        source: 'omt',
        'source-layer': 'transportation',
        minzoom: 6,
        filter: ['==', ['get', 'class'], 'motorway'],
        paint: {
          'line-color': C.mapMotorway,
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 0.5, 10, 1.4, 14, 3],
        },
      },
      {
        id: 'aerodrome-area',
        type: 'fill',
        source: 'omt',
        'source-layer': 'aeroway',
        minzoom: 9,
        filter: ['all', ['==', ['geometry-type'], 'Polygon'], ['==', ['get', 'class'], 'aerodrome']],
        paint: { 'fill-color': C.mapAerodrome, 'fill-opacity': 0.8 },
      },
      {
        id: 'runway-area',
        type: 'fill',
        source: 'omt',
        'source-layer': 'aeroway',
        minzoom: 9,
        filter: ['all', ['==', ['geometry-type'], 'Polygon'], ['==', ['get', 'class'], 'runway']],
        paint: { 'fill-color': C.mapRunway },
      },
      {
        id: 'runway',
        type: 'line',
        source: 'omt',
        'source-layer': 'aeroway',
        minzoom: 8,
        filter: ['all', ['==', ['geometry-type'], 'LineString'], ['==', ['get', 'class'], 'runway']],
        paint: {
          'line-color': C.mapRunway,
          'line-width': ['interpolate', ['exponential', 2], ['zoom'], 8, 1, 12, 5, 15, 30],
        },
      },
      {
        id: 'country-label',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'place',
        maxzoom: 7,
        filter: ['==', ['get', 'class'], 'country'],
        layout: {
          'text-field': ['upcase', ['coalesce', ['get', 'name:de'], ['get', 'name']]],
          'text-font': FONT,
          'text-size': 11,
          'text-letter-spacing': 0.25,
        },
        paint: { 'text-color': C.mapCountryLabel, 'text-halo-color': C.mapLand, 'text-halo-width': 1 },
      },
      {
        id: 'village-label',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'place',
        minzoom: 10,
        filter: ['in', ['get', 'class'], ['literal', ['village', 'suburb']]],
        layout: {
          'text-field': ['coalesce', ['get', 'name:de'], ['get', 'name']],
          'text-font': FONT,
          'text-size': 11,
        },
        paint: { 'text-color': C.mapVillageLabel, 'text-halo-color': C.mapLand, 'text-halo-width': 1.2 },
      },
      {
        id: 'town-label',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'place',
        minzoom: 7,
        filter: ['==', ['get', 'class'], 'town'],
        layout: {
          'text-field': ['coalesce', ['get', 'name:de'], ['get', 'name']],
          'text-font': FONT,
          'text-size': ['interpolate', ['linear'], ['zoom'], 7, 11, 12, 13],
        },
        paint: { 'text-color': C.mapTownLabel, 'text-halo-color': C.mapLand, 'text-halo-width': 1.2 },
      },
      {
        id: 'city-label',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'place',
        minzoom: 4,
        filter: ['==', ['get', 'class'], 'city'],
        layout: {
          'text-field': ['coalesce', ['get', 'name:de'], ['get', 'name']],
          'text-font': FONT_BOLD,
          'text-size': ['interpolate', ['linear'], ['zoom'], 4, 11, 8, 14, 12, 17],
          'symbol-sort-key': ['coalesce', ['get', 'rank'], 99],
        },
        paint: { 'text-color': C.mapCityLabel, 'text-halo-color': C.mapLand, 'text-halo-width': 1.4 },
      },
      {
        id: 'aerodrome-dot',
        type: 'circle',
        source: 'omt',
        'source-layer': 'aerodrome_label',
        minzoom: 6,
        filter: ['any', ['==', ['get', 'class'], 'international'], ['>=', ['zoom'], 8.5]],
        paint: {
          'circle-radius': 3,
          'circle-color': C.bg,
          'circle-stroke-color': C.textSecondary,
          'circle-stroke-width': 1.2,
        },
      },
      {
        id: 'aerodrome-label',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'aerodrome_label',
        minzoom: 6,
        filter: ['any', ['==', ['get', 'class'], 'international'], ['>=', ['zoom'], 8.5]],
        layout: {
          'text-field': [
            'step',
            ['zoom'],
            ['coalesce', ['get', 'iata'], ['get', 'icao'], ''],
            9,
            ['concat', ['coalesce', ['get', 'iata'], ['get', 'icao'], ''], '\n', ['coalesce', ['get', 'name:de'], ['get', 'name'], '']],
          ],
          'text-font': FONT_BOLD,
          'text-size': 10,
          'text-letter-spacing': 0.08,
          'text-offset': [0, 1.1],
          'text-anchor': 'top',
        },
        paint: { 'text-color': C.mapAirportLabel, 'text-halo-color': C.mapLand, 'text-halo-width': 1.2 },
      },
    ],
  };
}
