// Writes intel/src/data/members.ts and mdb-bluesky.ts from the results of the test lab (lab/politics.mjs).
// Usage: git fetch origin lab-results && node scripts/members.mjs
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const show = (file) => JSON.parse(execFileSync('git', ['show', `origin/lab-results:${file}`], { encoding: 'utf8', maxBuffer: 1 << 26 }));
const PARTY = { 'CDU/CSU': 'cdu', AfD: 'afd', SPD: 'spd', 'BÜNDNIS 90/DIE GRÜNEN': 'gruene', 'Die Linke': 'linke', fraktionslos: 'fl' };
// abgeordnetenwatch writes "BÜNDNIS 90/­DIE GRÜNEN (Bundestag 2025 - 2029)", with a soft hyphen.
const party = (fraction) => PARTY[fraction.replace(/­/g, '').replace(/\s*\(.*\)$/, '')];
const day = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

const mps = show('mps.json').filter((m) => party(m.fraction));
const byParty = Object.values(PARTY).map((p) => `  ${p}: ${JSON.stringify(mps.filter((m) => party(m.fraction) === p).map((m) => m.name).sort((a, b) => a.localeCompare(b, 'de')))},`);
writeFileSync(
  'intel/src/data/members.ts',
  `// Members of the 21st Bundestag (2025 to 2029) with their fraction, from abgeordnetenwatch.de (CC0), period 161.
// Generated by scripts/members.mjs from the test lab (lab/politics.mjs), ${mps.length} members with a running mandate on ${day}.
import type { PartyId } from './parties';

export const MEMBERS: Record<PartyId, string[]> = {
${byParty.join('\n')}
};
`,
);

const bsky = show('mdb-bluesky.json').filter((b) => b.handle !== 'handle.invalid' && party(b.fraction));
writeFileSync(
  'intel/src/data/mdb-bluesky.ts',
  `// Members of the Bundestag on Bluesky: profiles of the Bluesky search that match a member of members.ts by name.
// Generated by scripts/members.mjs from the test lab (lab/politics.mjs), ${bsky.length} profiles on ${day}, most followers first.
// Loaded only by the collector, too many accounts for every refresh of the app.
import type { PartyId } from './parties';

export const MDB_BLUESKY: [handle: string, name: string, party: PartyId][] = [
${bsky.map((b) => `  [${JSON.stringify(b.handle)}, ${JSON.stringify(b.name)}, '${party(b.fraction)}'],`).join('\n')}
];
`,
);
console.log(`${mps.length} members, ${bsky.length} on Bluesky`);
